routes/web.php
        Route::any('saveEdit/{id}', 'TagController@update')->name('saveEdit');

        // data select2
        Route::any('dataSelect2', 'TagController@dataSelect2')->name('data_select2');
        Route::any('dataSelect2_ch', 'TagController@dataSelect2_ch')->name('dataSelect2_ch');
        Route::any('dataTable', 'TagController@dataTable')->name('dataTable');
        Route::any('remove', 'TagController@destroy')->name('remove');

        Route::any('dataSelect21', 'TagController@dataSelect2')->name('data_select21');

        Route::any('saveAdd', 'TagController@store')->name('saveAdd');

    });

    /*
     * Route Group Category
     */
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        // index
        Route::any('/', 'CategoryController@index')->name('index');
        // data categories
        Route::get('data', 'CategoryController@dataCategories')->name('data');
        Route::get('edit/{id?}', 'CategoryController@edit')->name('edit');
        Route::any('data_select2', 'CategoryController@dataCategories_select2')->name('data_select2');
        Route::any('data_select2_pa', 'CategoryController@dataCategories_select2_pa')->name('data_select2_pa');

        Route::any('get_child_cat_by_id_current', 'CategoryController@get_child_cat_by_id_current')->name('get_child_cat_by_id_current');
        //post create category
        Route::any('postCategory', 'CategoryController@store')->name('postCategory');
        //update category
        Route::any('updateCategory', 'CategoryController@update')->name('updateCategory');
        // remove category
        Route::any('remove', 'CategoryController@destroy')->name('remove');
    });

    /*
     * Route Group Artists
     */
    Route::group(['prefix' => 'artists', 'as' => 'artists.'], function () {
        // index
        Route::any('/', 'ArtistController@index')->name('index');
        // data artists
        Route::get('data', 'ArtistController@data')->name('data');

        Route::get('add', 'ArtistController@add')->name('add');

        Route::post('saveAdd', 'ArtistController@saveAdd')->name('saveAdd');

        Route::get('edit/{id?}', 'ArtistController@edit')->name('edit');

        Route::post('saveEdit', 'ArtistController@saveEdit')->name('saveEdit');

        Route::get('detail/{id}', 'ArtistController@detail');

        Route::get('delete/{id}', 'ArtistController@delete');

        Route::any('data_select2', 'ArtistController@dataSelect2')->name('data_select2');

        Route::post('deleteMulti', 'ArtistController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group User
     */
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index');

        Route::get('data', 'UserController@data')->name('data');

        Route::get('delete/{id}', 'UserController@delete');

        Route::get('add', 'UserController@add')->name('add');

        Route::post('saveAdd', 'UserController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'UserController@edit');

        Route::post('saveEdit', 'UserController@saveEdit')->name('saveEdit');

        Route::get('profile', 'UserController@profile')->name('profile');

        Route::post('saveProfile', 'UserController@saveProfile')->name('saveProfile');
    });

    /*
     * Route Group Customer
     */

    Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('data', 'CustomerController@data')->name('data');

        Route::get('add', 'CustomerController@add')->name('add');
        Route::post('saveAdd', 'CustomerController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'CustomerController@edit');
        Route::post('saveEdit', 'CustomerController@saveEdit')->name('saveEdit');

        Route::get('detail/{id}', 'CustomerController@detail');

        Route::get('delete/{id?}', 'CustomerController@delete')->name('delete');

        Route::post('deleteMulti', 'CustomerController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group Album
     */

    Route::group(['prefix' => 'albums', 'as' => 'albums.'], function () {
        Route::get('/', 'AlbumController@index')->name('index');
        Route::get('data', 'AlbumController@data')->name('data');
        Route::any('data_select2', 'AlbumController@dataSelect2')->name('data_select2');

        //save create ablum
        Route::any('saveAdd', 'AlbumController@saveAdd')->name('saveAdd');

        // save edit album
        Route::get('edit/{id?}', 'AlbumController@edit')->name('edit');

        Route::any('saveEdit', 'AlbumController@saveEdit')->name('saveEdit');

        Route::get('delete/{id}', 'AlbumController@delete');
    });
    /*
     * Route Group Page
     */

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index')->name('index');

        Route::get('data', 'PageController@data')->name('data');

        Route::get('add', 'PageController@add')->name('add');

        Route::post('saveAdd', 'PageController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'PageController@edit');

        Route::post('saveEdit', 'PageController@saveEdit')->name('saveEdit');

        Route::get('delete/{id}', 'PageController@delete');

        Route::post('deleteMulti', 'PageController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group Post
     */

    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/', 'PostController@index')->name('index');

        Route::get('data', 'PostController@data')->name('data');

        Route::get('add', 'PostController@add')->name('add');

        Route::post('saveAdd', 'PostController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'PostController@edit');

        Route::post('saveEdit', 'PostController@saveEdit')->name('saveEdit');

        Route::get('delete/{id}', 'PostController@delete');

        Route::post('deleteMulti', 'PostController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group Playlist
     **/
    Route::group(['prefix' => 'playlists', 'as' => 'playlists.'], function () {
        Route::get('/', 'PlaylistController@index')->name('index');

        Route::get('add', 'PlaylistController@add')->name('add');

        Route::post('saveAdd', 'PlaylistController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'PlaylistController@edit')->name('edit');

        Route::post('saveEdit', 'PlaylistController@saveEdit')->name('saveEdit');

        Route::post('delete', 'PlaylistController@delete')->name('delete');

        Route::post('deleteMulti', 'PlaylistController@deleteMulti')->name('deleteMulti');
        Route::any('multiDel', 'PlaylistController@multiDel')->name('multiDel');
        Route::any('setActiveStatus', 'PlaylistController@setActiveStatus')->name('setActiveStatus');
        Route::any('setActiveStatusAll', 'PlaylistController@setActiveStatusAll')->name('setActiveStatusAll');
    });

    /*
     * Route Group Lyric
     **/
    Route::group(['prefix' => 'lyrics', 'as' => 'lyrics.'], function () {
        Route::post('dataSelect2', 'LyricController@dataSelect2')->name('data_select2');
    });

    /*
     * Route Group Video
     **/
    Route::group(['prefix' => 'videos', 'as' => 'videos.'], function () {
        Route::post('dataSelect2', 'VideoController@dataSelect2')->name('data_select2');
    });

    /*
     * Route Group Options
     **/
    Route::group(['prefix' => 'options', 'as' => 'options.'], function () {
        Route::get('generals', 'OptionController@general')->name('generals');
        Route::post('save_general', 'OptionController@save_general')->name('save_general');
        /*
         * today listen
         */
        Route::any('todaylisten', 'OptionController@todaylisten')->name('todaylisten');

        Route::get('menu_footer', 'OptionController@menu_footer')->name('menu_footer');
        Route::post('save_menu_footer', 'OptionController@save_menu_footer')->name('save_menu_footer');

        Route::get('sort_category', 'OptionController@sort_category')->name('sort_category');
        Route::post('save_sort_category', 'OptionController@save_sort_category')->name('save_sort_category');

        Route::get('choose_category_bxh', 'OptionController@choose_category_bxh')->name('choose_category_bxh');
        Route::post('save_choose_category2', 'OptionController@save_choose_category2')->name('save_choose_category2');
        Route::post('save_choose_category', 'OptionController@save_choose_category')->name('save_choose_category');
    });

    /*
     * Route Group Topics
     **/
    Route::group(['prefix' => 'topics', 'as' => 'topics.'], function () {
        Route::get('/', 'TopicController@index')->name('index');
        Route::get('add', 'TopicController@create')->name('add');
        Route::get('delete/{id}', 'TopicController@destroy')->name('delete');
        Route::post('saveAdd', 'TopicController@store')->name('saveAdd');
        Route::any('dataSelect2', 'TopicController@dataSelect2')->name('dataSelect2');
        Route::post('deleteMulti', 'TopicController@deleteMulti')->name('deleteMulti');
    });
});

// Route::get('/', function () {
//     return view('welcome');
// });php
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
    // Route::get('/','Auth\LoginController@login');
    // Route::get('home', 'AdminController@index')->name('home');

    Route::get('login', 'Auth\LoginController@login')->name('login');
    Route::post('postLogin', 'Auth\LoginController@postLogin')->name('postLogin');
    Route::get('forgetPassword', 'Auth\LoginController@forgetPassword')->name('forgetPassword');

    Route::post('postForget', 'Auth\LoginController@postForget')->name('postForget');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Customer extends Authenticatable
{
    protected $table = 'customers';

    public $fillable = [
        'username',
        'token',
        'name',
        'email',
        'phone',
        'avatar',
        'created_at',
        'updated_at',
        'views',
    ];

    protected $hidden = [
        'password',
    ];
    public function customer()
    {
        return $this->belongsTo('App\Models\Customer', 'email', 'email');
    }
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;
use App\Models\Customer;
use App\Http\Requests\RequestAddCustomer;
use App\Http\Requests\RequestEditCustomer;

class CustomerController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    public function index(){
        return view('admin.customers.index');
    }

    public function data(){
        $data = Customer::all()->sortByDesc('created_at');
        return Datatables::of($data)->make(true);
    }

    public function edit($id){
        $customer = Customer::find($id);
        return view('admin.customers.edit', ['customer' => $customer]);
    }

    public function saveEdit(RequestEditCustomer $request){
        // dd($request->all());

        $customerCurrent = Customer::find($request->id);
        $data = $request->except('_token','id','image');
        if (empty($request->password)) {
            $data['password'] = $customerCurrent->password;
        }else{
            $data['password'] = bcrypt($request->password);
        }

        $data['avatar'] = $request->image;

        $result = Customer::where('id',$request->id)->update($data);

        if ($result == 1) {
            return redirect()->route('admin.customers.index')->with('success', 'Sửa người dùng thành công');
        } else {
            return redirect()->route('admin.customers.index')->with('error', 'Sửa người dùng không thành công');
        }

    }

    public function add(){
        return view('admin.customers.add');
    }
    public function saveAdd(RequestAddCustomer $request){
        $data = $request->except('_token','cf_password','image');
        $data['password'] = bcrypt($request->password);
        $data['avatar'] = $request->image;
        $data['created_at'] = date('Y-m-d H:i:s', time());
        $result = Customer::insert($data);
        if ($result == 1) {
            return redirect()->route('admin.customers.index')->with('success', 'Thêm người dùng thành công');
        } else {
            return redirect()->route('admin.customers.index')->with('error', 'Có lỗi xảy ra');
        }
    }

    public function detail($id){
        $customer = Customer::find($id);
        return view('admin.customers.detail',['customer' => $customer]);
    }

    public function delete(Request $request){
        $result = Customer::where('id',$request->id)->delete();
        if ($result == 1) {
            return redirect()->route('admin.customers.index')->with('success', 'Xóa người dùng thành công');
        } else {
            return redirect()->route('admin.customers.index')->with('error', 'Có lỗi xảy ra');
        }
    }

    public function deleteMulti(Request $request)
    {
        $data = $request->data;

        $arr = explode(',', $data);
        $check = Customer::destroy($arr);
        if ($check) {
            return response()->json([
                'error' => false,
                'message' => 'success',
                'data' => $arr,
            ]);
        } else {
            return response()->json([
                'error' => true,
                'message' => 'Có gì đó sai sai',
                'data' => $arr,
            ]);
        };
    }

}

resources/views/admin/customers/add.blade.php
@extends('admin.layout.master')


{{-- page title --}}
@section('page_title')
Danh sách người dùng
@endsection


{{-- style --}}
@section('style')
<style>
    .cke_contents {
        min-height: 100px !important;
    }
</style>
@endsection


{{-- content --}}
@section('content')

{{-- alert --}}
@if (session('success'))
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-success alert-dismissible show" role="alert">
            <strong>Thông báo!</strong> {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
@endif

@if (session('error'))
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-warning alert-dismissible show" role="alert">
            <strong>Thông báo!</strong> {{ session('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
@endif
{{-- end alert --}}


<!-- main content -->
<div class="row">
    <div class="col-sm-12">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">
                    Thêm mới người dùng
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title=""
                        data-original-title="Collapse">
                        <i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <!--  content here -->
                <form method="POST" action="{{route('admin.customers.saveAdd')}}">
                    {{@csrf_field()}}
                    <div class="row">
                    <div class="col-sm-7">
                        <div class="form-group">
                            <label for="name">Tài khoản đăng nhập</label>
                            <input class="form-control" type="text" name="username" id="username" value="{{ !empty(old('username')) ? old('username') : ''}}">
                            @error('username')
                            <span style="color:red">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="name">Tên người dùng</label>
                            <input class="form-control" type="text" name="name" id="name"
                                value="{{ !empty(old('name')) ? old('name') : ''}}">
                            @error('name')
                            <span style="color:red">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input class="form-control" type="text" name="email" id="email"
                                value="{{ !empty(old('email')) ? old('email') : ''}}">
                            @error('email')
                            <span style="color:red">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="phone">Số điện thoại</label>
                            <input class="form-control" type="number" name="phone" id="phone" value="{{ !empty(old('phone')) ? old('phone') : ''}}">

                        </div>
                        <div class="form-group">
                            <label for="password">Mật khẩu</label>
                            <input class="form-control" type="password" name="password" id="password"
                                value="{{ !empty(old('password')) ? old('password') : ''}}">
                            @error('password')
                            <span style="color:red">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="password">Xác nhận mật khẩu</label>
                            <input class="form-control" type="password" name="cf_password" id="cf_password"
                                value="{{ !empty(old('cf_password')) ? old('cf_password') : ''}}">
                            @error('cf_password')
                            <span style="color:red">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="status">Trạng thái</label>
                            <select name="status" id="status" class="form-control">
                                <option value="0">Không kích hoạt</option>
                                <option value="1">Kích hoạt</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label for="image">Avatar</label>
                            <input  value="{{ (old('image')) ? old('image') : ( !empty($product['image']) ? $product['image'] : '' ) }}" readonly
                                min="0" type="hidden" name="image" class="form-control image" id="thumbnail">
                        </div>
                        <button class="btn btn-primary choose_image" id="choose_image" type="button">Choose Image</button>
                        <br>
                        <div class=form-group>
                            <img style="width: auto; height: 350px; padding-top: 10px !important" id="this-img"
                                src="{{ (old('image')) ? old('image') : ( !empty($product['image']) ? $product['image'] : '' ) }}" alt="">
                        </div>
                    </div>
                    </div>
                    <div class="form-group">
                        <button class=" btn btn-success" type="submit">Lưu</button>
                    </div>
                </form>
                <!-- end content here -->
            </div>
        </div>
    </div>
    {{-- /////////////////// --}}

</div>
<!-- end main content -->




@endsection
<!----- end javascript here -------->
@section('js')

{{-- ckfinder --}}
<script type="text/javascript" src="/js/ckfinder/ckfinder.js"></script>
<script>
    CKFinder.config( { connectorPath: '/ckfinder/connector' } );
</script>

{{-- js --}}
@if ((old('image')))
<script>
    $('img#this-img').show();
</script>
@else
@if (!empty($product['image']))
<script>
    $('img#this-img').show();
</script>
@else
<script>
    $('img#this-img').hide();
</script>
@endif
@endif
<script>
    var button1 = document.getElementById('choose_image');

    button1.onclick = function() {
        selectFileWithCKFinder( 'thumbnail' );
    };

    function selectFileWithCKFinder( elementId, elementImg ) {
        CKFinder.popup( {
            resourceType: 'Images',
            chooseFiles: true,
            width: 800,
            height: 600,
            onInit: function( finder ) {
                finder.on( 'files:choose', function( evt ) {
                    var file = evt.data.files.first();
                    var output = document.getElementById( elementId );
                    output.value = file.getUrl();
                    $('img#this-img').show();
                    $('img#this-img').attr('src', file.getUrl());
                } );

                finder.on( 'file:choose:resizedImage', function( evt ) {
                    var output = document.getElementById( elementId );
                    output.value = evt.data.resizedUrl;
                } );
            }
        } );
    }
</script>
@endsection

resources/views/admin/customers/index.blade.php
@extends('admin.layout.master')


{{-- page title --}}
@section('page_title')
Danh sách người dùng
@endsection


{{-- style --}}
@section('style')
<style>
    .cke_contents {
        min-height: 100px !important;
    }
</style>
@endsection


{{-- content --}}
@section('content')

{{-- alert --}}
@if (session('success'))
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-success alert-dismissible show" role="alert">
            <strong>Thông báo!</strong> {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
@endif

@if (session('error'))
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-warning alert-dismissible show" role="alert">
            <strong>Thông báo!</strong> {{ session('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
@endif
{{-- end alert --}}


<!-- main content -->
<div class="row">

    {{-- /////////////////// --}}
    <div class="col-sm-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">
                    <a href="{{route('admin.customers.add')}}" class="btn btn-primary">Thêm</a>

                    {{-- Danh sách quản trị --}}
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title=""
                        data-original-title="Collapse">
                        <i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <div class="col-xs-12">
                    <form class="form-action" id="form-action">
                        <div style="margin-right: 5px !important;" class="pull-left">
                            <select name="action" id="action" class="form-control input-sm action" field_signature="2473543864">
                                <option value="0">Tác vụ</option>
                                <option value="delete">Xoá</option>
                            </select>
                        </div>
                        <div class="pull-left">
                            <button id="btn-action" class="btn btn-secondary btn-sm btn-flat btn-action">Áp
                                dụng</button>
                        </div>
                    </form>
                </div>
                <!--  content here -->
                <div class="col-xs-12">
                    <div class="table-responsive">
                        <table class="table table-hover table-striped" id="table-customers"></table>
                    </div>
                </div>



                <!-- end content here -->
            </div>
        </div>
    </div>
</div>
<!-- end main content -->








<!----- javascript here -------->
@section('js')
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script>
    $(function () {

        var table = $('#table-customers').DataTable({

            serverSide: true,
            processing: true,
            responsive: true,
            "bLengthChange" : false,
            ajax: "{{ route('admin.customers.data') }}",
            // order: [
            //     [0, 'desc']
            // ],
            lengthMenu: [20, 30, 50, 100],
            iDisplayLength: 20,
            columnDefs: [{
                    "targets": [0],
                    "searchable": false,
                    "orderable": false,
                },
                {
                    "targets": [1],
                    "searchable": false,
                    "orderable": false,
                },
                {
                    "targets": [2],
                    "searchable": true,
                    "orderable": true,
                },
                {
                    "targets": [3],
                    "searchable": true,
                    "orderable": true,
                },
                {
                    "targets": [4],
                    "searchable": true,
                    "orderable": true,
                },
                {
                    "targets": [5],
                    "searchable": true,
                    "orderable": true,
                }
            ],
            columns: [
                {
                    data: 'id',
                    title: `<input id="checkAll" value="all" class="checkAll" type="checkbox" name="checkAll"> `,
                    render:function (data) {
                        var html = `<td>
                                        <input type="checkbox" class="checkbox" value="${data}" name="checkbox">
                                    </td>`;
                        return html;
                    }
                },
                {
                    data: 'id',
                    title: "ID"
                },
                {
                    data: 'username',
                    title: "Tên đăng nhập",
                    autoWidth: true
                },
                {
                    data: 'name',
                    title: "Tên người dùng",
                    autoWidth: true
                },
                {
                    data: 'email',
                    title: "Email",
                    autoWidth: true
                },
                {
                    data: 'status',
                    title: "Trạng thái",
                    autoWidth: true,
                    render: function (data) {
                    html = `${data}` == 1 ? 'Kích hoạt' : 'Không kích hoạt'
                    ;
                    return html;
                    }
                },
                {
                    data: 'id',
                    title: 'Hành động',
                    autoWidth: true,
                    render: function (data) {
                        // console.log(data);
                        var html =
                            `
                            <a href="{{url('/').'/admin/customers/detail/'}}${data}" data-toggle="modal" class="btn btn-primary btn-xs"><i class="fa fa-info-circle"></i></a>
                            <a href="{{url('/').'/admin/customers/edit/'}}${data}" data-toggle="modal" class="btn btn-warning btn-xs"><i class="fa fa-pencil"></i></a>
                            <a url="{{url('/').'/admin/customers/delete/'}}${data}" data-toggle="modal" class="btn btn-danger btn-xs btn-delete"><i class="fa fa-remove"></i></a>
                            `;
                        return html;
                    }
                }

            ],
            "language": {
                "lengthMenu": "Hiển thị _MENU_ bản ghi trên trang",
                "zeroRecords": "Không có dữ liệu để hiển thị",
                "info": "Trang hiển thị _PAGE_ / _PAGES_",
                "infoEmpty": "Không có dữ liệu để hiển thị",
                "infoFiltered": "(được lọc từ _MAX_ tổng số hồ sơ)",
                "search": 'Tìm kiếm:   ',
                "paginate": {
                    "first": "Trang đầu",
                    "last": "Trang cuối",
                    "next": "Trang sau",
                    "previous": "Trang trước"
                },
            },
            initComplete: function() {
            $('body').on('click', '.btn-remove', function() {
                var id = $(this).data('remove');
                swal({
                    title: "Bạn có chắc chắn?",
                    text: "Sau khi xóa, bạn sẽ không thể khôi phục danh mục này!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                }).then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url: "{{ route('admin.customers.delete')}}",
                            method: 'POST',
                            data: {
                                id: id,
                                _token: '{{csrf_token()}}'
                            }
                        }).done(result => {
                            table.ajax.reload();
                        });
                    } else {

                    }
                    })
                })
            }


        })
    })
    $(function () {
        $('body').on('click', '#btn-action', function (e) {
            // console.log('a');
            e.preventDefault();
            var action = $('body').find('#action').val();
            if (parseInt(action) != 0) {
                if (action == 'delete') {
                    var data = [];
                    $.each($("input[name='checkbox']:checked"), function () {
                        data.push($(this).val());
                    });
                    // console.log(data);
                    if (data.length != 0) {
                        var c = confirm("Bạn có chắc chắn muốn xoá mục đã chọn?");
                        if (c === true) {
                            var formData = new FormData();
                            formData.append('data', data);
                            ajaxFunc("{{route('admin.customers.deleteMulti')}}", formData);
                        }
                    } else {
                        alert('Vui lòng chọn !')
                    }
                }
            }
        })
    })




</script>


@endsection
<!----- end javascript here -------->

@endsection