routes/web.php
Route::get('/clear-cache', function () {
    Artisan::call('cache:clear');

    return 'Cache is cleared';
});
/*
 * Route Admin
 */
Route::group(['prefix' => 'admin', 'middleware' => ['auth'], 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::post('ckeditor/image_upload', 'CKEditorController@upload')->name('upload');
    /*
     * Dashboard
     */
    Route::get('home', 'HomeController@index')->name('home');
    Route::get('/', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
        Route::get('/', 'CommentController@index')->name('index');
        Route::post('delete', 'CommentController@destroy')->name('delete');
        Route::post('deleteMulti', 'CommentController@deleteMulti')->name('deleteMulti');
        Route::post('updateStatus', 'CommentController@updateStatus')->name('updateStatus');
        Route::post('acceptAll', 'CommentController@acceptAll')->name('acceptAll');
        Route::post('accept', 'CommentController@accept')->name('accept');
    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/', 'ReportController@index')->name('index');
        Route::post('updateStatus', 'ReportController@updateStatus')->name('updateStatus');
        Route::post('delete', 'ReportController@destroy')->name('delete');
        Route::post('deleteMulti', 'ReportController@deleteMulti')->name('deleteMulti');
    });
    /*
     * Route Songs
     */
    Route::group(['prefix' => 'songs', 'as' => 'songs.'], function () {
        Route::get('/', 'SongController@index')->name('index');

        Route::get('add', 'SongController@create')->name('add');

        Route::get('edit/{id}', 'SongController@edit')->name('edit');
        Route::post('delete', 'SongController@destroy')->name('delete');
        //save create ablum
        Route::any('postSong', 'SongController@store')->name('postSong');
        //save edit song
        Route::any('updateSong', 'SongController@update')->name('updateSong');
        Route::any('multiDel', 'SongController@multiDel')->name('multiDel');
        Route::any('setActiveStatus', 'SongController@setActiveStatus')->name('setActiveStatus');
        Route::any('setActiveStatusAll', 'SongController@setActiveStatusAll')->name('setActiveStatusAll');
    });
    Route::group(['prefix' => 'videos', 'as' => 'videos.'], function () {
        Route::get('/', 'VideoController@index')->name('index');
        Route::get('add', 'VideoController@create')->name('add');
        Route::post('saveAdd', 'VideoController@store')->name('saveAdd');

        Route::post('delete', 'VideoController@destroy')->name('delete');
        Route::post('deleteMulti', 'VideoController@deleteMulti')->name('deleteMulti');
        Route::any('multiDel', 'VideoController@multiDel')->name('multiDel');

        Route::get('edit/{id}', 'VideoController@edit')->name('edit');
        Route::post('saveEdit/{id}', 'VideoController@update')->name('saveEdit');
        ############-
        Route::get('custom', 'VideoController@custom')->name('custom');
        Route::any('setActiveStatusAll', 'VideoController@setActiveStatusAll')->name('setActiveStatusAll');
        Route::any('setActiveStatus', 'VideoController@setActiveStatus')->name('setActiveStatus');
    });
    /*
     * Route Tags
     */
    Route::group(['prefix' => 'tags', 'as' => 'tags.'], function () {
        Route::get('/', 'TagController@index')->name('index');

        Route::get('add', 'TagController@create')->name('add');
        //save create ablum
        Route::any('postTag', 'TagController@store')->name('postSong');
        Route::get('edit/{id?}', 'TagController@edit')->name('edit');
        Route::any('saveEdit/{id}', 'TagController@update')->name('saveEdit');

        // data select2
        Route::any('dataSelect2', 'TagController@dataSelect2')->name('data_select2');
        Route::any('dataSelect2_ch', 'TagController@dataSelect2_ch')->name('dataSelect2_ch');
        Route::any('dataTable', 'TagController@dataTable')->name('dataTable');
        Route::any('remove', 'TagController@destroy')->name('remove');

        Route::any('dataSelect21', 'TagController@dataSelect2')->name('data_select21');

        Route::any('saveAdd', 'TagController@store')->name('saveAdd');

    });

    /*
     * Route Group Category
     */
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function () {
        // index
        Route::any('/', 'CategoryController@index')->name('index');
        // data categories
        Route::get('data', 'CategoryController@dataCategories')->name('data');
        Route::get('edit/{id?}', 'CategoryController@edit')->name('edit');
        Route::any('data_select2', 'CategoryController@dataCategories_select2')->name('data_select2');
        Route::any('data_select2_pa', 'CategoryController@dataCategories_select2_pa')->name('data_select2_pa');

        Route::any('get_child_cat_by_id_current', 'CategoryController@get_child_cat_by_id_current')->name('get_child_cat_by_id_current');
        //post create category
        Route::any('postCategory', 'CategoryController@store')->name('postCategory');
        //update category
        Route::any('updateCategory', 'CategoryController@update')->name('updateCategory');
        // remove category
        Route::any('remove', 'CategoryController@destroy')->name('remove');
    });

    /*
     * Route Group Artists
     */
    Route::group(['prefix' => 'artists', 'as' => 'artists.'], function () {
        // index
        Route::any('/', 'ArtistController@index')->name('index');
        // data artists
        Route::get('data', 'ArtistController@data')->name('data');

        Route::get('add', 'ArtistController@add')->name('add');

        Route::post('saveAdd', 'ArtistController@saveAdd')->name('saveAdd');

        Route::get('edit/{id?}', 'ArtistController@edit')->name('edit');

        Route::post('saveEdit', 'ArtistController@saveEdit')->name('saveEdit');

        Route::get('detail/{id}', 'ArtistController@detail');

        Route::get('delete/{id}', 'ArtistController@delete');

        Route::any('data_select2', 'ArtistController@dataSelect2')->name('data_select2');

        Route::post('deleteMulti', 'ArtistController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group User
     */
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index');

        Route::get('data', 'UserController@data')->name('data');

        Route::get('delete/{id}', 'UserController@delete');

        Route::get('add', 'UserController@add')->name('add');

        Route::post('saveAdd', 'UserController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'UserController@edit');

        Route::post('saveEdit', 'UserController@saveEdit')->name('saveEdit');

        Route::get('profile', 'UserController@profile')->name('profile');

        Route::post('saveProfile', 'UserController@saveProfile')->name('saveProfile');
    });

    /*
     * Route Group Customer
     */

    Route::group(['prefix' => 'customers', 'as' => 'customers.'], function () {
        Route::get('/', 'CustomerController@index')->name('index');
        Route::get('data', 'CustomerController@data')->name('data');

        Route::get('add', 'CustomerController@add')->name('add');
        Route::post('saveAdd', 'CustomerController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'CustomerController@edit');
        Route::post('saveEdit', 'CustomerController@saveEdit')->name('saveEdit');

        Route::get('detail/{id}', 'CustomerController@detail');

        Route::get('delete/{id?}', 'CustomerController@delete')->name('delete');

        Route::post('deleteMulti', 'CustomerController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group Album
     */

    Route::group(['prefix' => 'albums', 'as' => 'albums.'], function () {
        Route::get('/', 'AlbumController@index')->name('index');
        Route::get('data', 'AlbumController@data')->name('data');
        Route::any('data_select2', 'AlbumController@dataSelect2')->name('data_select2');

        //save create ablum
        Route::any('saveAdd', 'AlbumController@saveAdd')->name('saveAdd');

        // save edit album
        Route::get('edit/{id?}', 'AlbumController@edit')->name('edit');

        Route::any('saveEdit', 'AlbumController@saveEdit')->name('saveEdit');

        Route::get('delete/{id}', 'AlbumController@delete');
    });
    /*
     * Route Group Page
     */

    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
        Route::get('/', 'PageController@index')->name('index');

        Route::get('data', 'PageController@data')->name('data');

        Route::get('add', 'PageController@add')->name('add');

        Route::post('saveAdd', 'PageController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'PageController@edit');

        Route::post('saveEdit', 'PageController@saveEdit')->name('saveEdit');

        Route::get('delete/{id}', 'PageController@delete');

        Route::post('deleteMulti', 'PageController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group Post
     */

    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/', 'PostController@index')->name('index');

        Route::get('data', 'PostController@data')->name('data');

        Route::get('add', 'PostController@add')->name('add');

        Route::post('saveAdd', 'PostController@saveAdd')->name('saveAdd');

        Route::get('edit/{id}', 'PostController@edit');

        Route::post('saveEdit', 'PostController@saveEdit')->name('saveEdit');

        Route::get('delete/{id}', 'PostController@delete');

        Route::post('deleteMulti', 'PostController@deleteMulti')->name('deleteMulti');
    });

    /*
     * Route Group Playlist
     **/

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = 'tags';
    protected $fillable = [
        'id',
        'title',
        'slug',
    ];

    public function songs()
    {
        return $this->belongsToMany('App\Models\Song', 'tag_song', 'tag_id', 'song_id');
    }
    public function getParent()
    {
        return self::where('id', '=', $this->parent_id)->first();
    }

    public function getChilden(Type $var = null)
    {
        return self::where('parent_id', '=', $this->id)
            ->orderBy('title', 'ASC')
            ->orderBy('id', 'ASC')
            ->get();
    }

    public function tags()
    {
        return $this->hasMany('App\Models\Tag', 'parent_id', 'id');
    }

    public function getTagChildren()
    {
        return $this->tags()->orderBy('title', 'ASC');
    }

    public function existInChilden($slug)
    {
        return $this->tags()->where('slug', '=', $slug)->exists();
    }

    public function countChilden()
    {
        return $this->tags()->count();
    }

}

app/Http/Controllers/Client/TagController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Playlist;
use App\Models\Tag;

class TagController extends Controller
{
    private $params = [
        '0' => 'p1',
        '1' => 'p2',
        '2' => 'p3',
        '3' => 'p4',
    ];
    public function index($p1 = null, $p2 = null, $p3 = null, $p4 = null)
    {
        $pa = Tag::where('parent_id', '=', 0)->with('getTagChildren')->orderBy('created_at', 'ASC')->get();
        $params = $this->params;
        $pargs = [];
        foreach ($pa as $key => $value) {

            $params[$key] = $$value;
            if ($$value != null) {
                $pargs[$key] = $$value;
            }
        }
        $arg = function ($value) {
            if ($value != null) {
                return ['tags.slug', '=', $value];
            }
        };
        // dd($pargs);
        $args = array_values(array_map($arg, $pargs));
        dd($pargs);
        $playlists = Playlist::join('tag_playlist', 'playlists.id', '=', 'tag_playlist.playlist_id')
            ->join('tags', 'tag_playlist.tag_id', '=', 'tags.id')
            ->where($args)->groupBy('playlists.id')->orderby('playlists.name')->get();
        // dd($playlists);

        // dd($pa);

        return view('client.tag', compact('pa', 'params', 'playlists', 'pargs'));
    }

}

resources/views/admin/tags/edit.blade.php
@extends('admin.layout.master')


{{-- page title --}}
@section('page_title')
Tag bài hát
@endsection


{{-- style --}}
@section('style')
<style>
    .select2 {
        width: 100% !important;
    }

</style>
@endsection


{{-- content --}}
@section('content')

{{-- alert --}}
@if (session('success'))
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-success alert-dismissible show" role="alert">
            <strong>Thông báo!</strong> {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
@endif

@if (session('error'))
<div class="row">
    <div class="col-sm-12">
        <div class="alert alert-warning alert-dismissible show" role="alert">
            <strong>Thông báo!</strong> {{ session('error') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
</div>
@endif
{{-- end alert --}}


<!-- main content -->
<div class="row">
    <div class="col-sm-6">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">
                    Sửa tag
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title=""
                        data-original-title="Collapse">
                        <i class="fa fa-minus"></i></button>
                </div>
            </div>
            <div class="box-body">
                <!--  content here -->
                <form id=create_category>
                    {{-- {{@csrf_field()}} --}}
                    <div class="form-group">
                        <label for="name">Tên tag</label>
                        <input class="form-control" type="text" name="title" id="title"
                            value="{{ $tag->title }}">
                        <div class="text-danger error_title" id="error_title"></div>
                    </div>
                    <div class="form-group">
                        <label for="slug">Slug</label>
                        <input class="form-control" type="text" name=slug id=slug
                            value="{{ $tag->slug }}">
                        <div class="text-danger error_slug" id="error_slug"></div>
                    </div>
                    <div class="form-group">
                        <label for="parent_id">Tag cha</label>
                        <select name="parent_id" id="parent_id" class="form-control parent_id">
                        </select>
                    </div>
                    <div class="form-group">
                        <button class=" btn btn-success" type="submit">Lưu</button>
                    </div>
                </form>
                <!-- end content here -->
            </div>
        </div>
    </div>

</div>
<!-- end main content -->
<!----- javascript here -------->
@section('js')

<script>
    $(function () {
        $('#title').on('keyup', function () {
            ChangeToSlug('title', 'slug');
        })
        $('#title2').on('keyup', function () {
            ChangeToSlug('title2', 'slug2');
        })
        function ChangeToSlug(n, s) {
            var title, slug;
            //Lấy text từ thẻ input title
            title = document.getElementById(n).value;
            //Đổi chữ hoa thành chữ thường
            slug = title.toLowerCase();
            //Đổi ký tự có dấu thành không dấu
            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
            slug = slug.replace(/đ/gi, 'd');
            //Xóa các ký tự đặt biệt
            slug = slug.replace(
                /\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
            //Đổi khoảng trắng thành ký tự gạch ngang
            slug = slug.replace(/ /gi, "-");
            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
            slug = slug.replace(/\-\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-/gi, '-');
            slug = slug.replace(/\-\-/gi, '-');
            //Xóa các ký tự gạch ngang ở đầu và cuối
            slug = '@' + slug + '@';
            slug = slug.replace(/\@\-|\-\@|\@/gi, '');
            //In slug ra textbox có id “slug”
            document.getElementById(s).value = slug;
        }
        // select2
        var select2 = $("#parent_id").select2({
            ajax: {
                url: "{{ route('admin.tags.data_select2') }}",
                type: "get",
                dataType: 'json',
                delay: 50,
                data: function (params) {
                    return {
                        q: $.trim(params.term),
                        _token: "{{csrf_token()}}"
                    };
                },
                processResults: function (data) {
                    var empt = [{
                        id: 0,
                        name: "-- không --"
                    }];
                    data = empt.concat(data);

                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.title,
                                id: item.id,
                                value: item.id
                            }
                        })
                    };
                },
                cache: true
            }
        });
        // thêm mới tag
        $('#create_category').on('submit', function (e) {
            e.preventDefault();
            // alert('ịijiij');
            var form = $(this);
            let dataForm = new FormData(form[0]);
            dataForm.set('_token', '{{csrf_token()}}');
            // console.log(dataForm);
            $.ajax({
                url: "{{route('admin.tags.saveEdit', ['id' => $tag->id])}}",
                // url: window.location.href,
                method: 'post',
                processData: false,
                contentType: false,
                data: dataForm,
            }).done(
                result => {
                    var msg = result.data;
                    if (result.errors) {
                        if (msg.title) {
                            form.find('#error_title').html(msg.title);
                            // console.log(msg.title);
                        }
                        if (msg.slug) {
                            form.find('#error_slug').html(msg.slug);
                            // console.log(msg.slug);
                        }
                    } else {
                        swal({
                            title: "Thông báo!",
                            text: "Cập nhật tag thành công!",
                            icon: "sussess",
                        }).then((all) => {
                            window.location.href = "{{ route('admin.tags.index') }}";
                        })
                    }
                });
        })
    })

</script>
@endsection
<!----- end javascript here -------->
@endsection